In [301]:
import numpy as np
from functools import partial

In [72]:
def test_func(polar):
#     polar = np.float(polar)
    x = polar[0] * np.sin(polar[1])
    y = polar[0] * np.cos(polar[1])
    return np.array([x,y])

In [254]:
def test_func_34(x):
    y = []
    y.insert(0, x[0])
    y.insert(1, 5 * x[2])
    y.insert(2, (4 * x[1] ** 2) - 2 * x[2])
    y.insert(3, x[2] * np.sin(x[0]))
    return np.array(y)
      

In [255]:
x_34 = np.array([np.pi/6, 0.1, 1])

In [256]:
test_func_34(x_34)

array([ 0.52359878,  5.        , -1.96      ,  0.5       ])

=== Example 2: polar-Cartesian transformation ===

The transformation from [[polar coordinate system|polar coordinates]] {{math|(''r'', ''φ'')}} to [[Cartesian coordinate system|Cartesian coordinates]] (''x'', ''y''), is given by the function {{math|'''F''': ℝ<sup>+</sup> × [0, 2{{pi}}) → ℝ<sup>2</sup>}} with components:

:<math>\begin{align}
x &= r \cos \varphi ; \\
y &= r \sin \varphi .
\end{align}</math>
:<math>\mathbf J(r, \varphi) = \begin{bmatrix}
  \dfrac{\partial x}{\partial r} & \dfrac{\partial x}{\partial\varphi}\\[1em]
  \dfrac{\partial y}{\partial r} & \dfrac{\partial y}{\partial\varphi} \end{bmatrix}
= \begin{bmatrix}
  \cos\varphi & - r\sin \varphi \\
  \sin\varphi &   r\cos \varphi \end{bmatrix}</math>

The Jacobian determinant is equal to {{math|''r''}}.  This can be used to transform integrals between the two coordinate systems:
:<math>\iint_{\mathbf F(A)} f(x, y) \,dx \,dy = \iint_A f(r \cos \varphi, r \sin \varphi) \, r \, dr \, d\varphi .</math>


:<math>\mathbf J_{\mathbf F}(x_1, x_2, x_3) = \begin{bmatrix}
  \dfrac{\partial y_1}{\partial x_1} & \dfrac{\partial y_1}{\partial x_2} & \dfrac{\partial y_1}{\partial x_3} \\[1em]
  \dfrac{\partial y_2}{\partial x_1} & \dfrac{\partial y_2}{\partial x_2} & \dfrac{\partial y_2}{\partial x_3} \\[1em]
  \dfrac{\partial y_3}{\partial x_1} & \dfrac{\partial y_3}{\partial x_2} & \dfrac{\partial y_3}{\partial x_3} \\[1em]
  \dfrac{\partial y_4}{\partial x_1} & \dfrac{\partial y_4}{\partial x_2} & \dfrac{\partial y_4}{\partial x_3} \end{bmatrix}
= \begin{bmatrix}
  1 & 0 & 0 \\
  0 & 0 & 5 \\
  0 & 8 x_2 & -2 \\
  x_3\cos x_1 & 0 & \sin x_1 \end{bmatrix}.</math>

In [3]:
def jac_test_func(polar):
    r = polar[0]
    phi = polar[1]
    jac = np.array([[np.cos(phi), -r * np.sin(phi)],
                    [np.sin(phi), r * np.cos(phi)]])
    
    return jac
    

In [197]:
def jac_test_func_34(x):
    jac = np.array([[1, 0, 0],
                    [0, 0, 5],
                    [0, 8 * x[1], -2],
                    [x[2]*np.cos(x[0]), 0, np.sin(x[0])] ])
    return jac

In [198]:
jac_test_func_34(x_34)

array([[ 1.       ,  0.       ,  0.       ],
       [ 0.       ,  0.       ,  5.       ],
       [ 0.       ,  0.8      , -2.       ],
       [ 0.8660254,  0.       ,  0.5      ]])

In [173]:
x = np.array([2.0, 0.1])

In [174]:
test_func(x)

array([ 0.19966683,  1.99000833])

In [175]:
jc = jac_test_func(x)
jc

array([[ 0.99500417, -0.19966683],
       [ 0.09983342,  1.99000833]])

In [277]:
def numerical_jacobian(f, x, eps=1e-5, *args):
    z = f(x, *args)
#     jacobian  = np.zeros((m,n), dtype=float)
    jacobian = []
    x_list = x.tolist()
    for i, data in enumerate(x_list):
        
        x1 = x.tolist()
        x1[i] = data + eps
        x1 = np.array(x1)
        jacobian.append((f(x1, *args) - z ) / eps)
    
    return np.array(jacobian).T

array([ 0. ,  5. , -2. ,  0.5])

In [257]:
f = test_func_34
z = f(x_34)
h = 1e-4
n = x.size
m = z.size
jacobian  = []

In [263]:
i = 2
x1 = x_34.tolist()
x1[i] = x_34[i] + h
x2 = np.array(x1)
x3 = (f(x2) - z ) / h
jacobian.append(x3)
# jacobian.append((f(x2) - z ) / h)

In [264]:
np.array(jacobian).T

array([[ 1.       ,  0.       ,  0.       ],
       [ 0.       ,  0.       ,  5.       ],
       [ 0.       ,  0.8004   , -2.       ],
       [ 0.8660004,  0.       ,  0.5      ]])

In [249]:
f(x2) 

array([ 0.        ,  0.        , -0.00041369,  0.        ])

In [248]:
f(x_34)

array([ 0.52359878,  5.        ,  1.17731294,  0.5       ])

In [252]:
4 * ((x2[1]) ** 2)

0.040080040000000004

In [253]:
4 * ((x_34[1]) ** 2)

0.040000000000000008

In [170]:
np.flip(np.array(jacobian), axis=1)

array([[  0.00000000e+00,   1.00000000e+00],
       [  2.00000000e+00,  -9.99999994e-05]])

In [282]:
x_34 = np.array([np.pi/2, 10.1, 3])

In [286]:
x

array([ 2. ,  0.1])

In [285]:
jac_test_func_34(x_34)

array([[  1.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   5.00000000e+00],
       [  0.00000000e+00,   8.08000000e+01,  -2.00000000e+00],
       [  1.83697020e-16,   0.00000000e+00,   1.00000000e+00]])

In [284]:
numerical_jacobian(test_func, x)

array([[ 0.09983342,  1.99000733],
       [ 0.99500417, -0.19967678]])

In [63]:
f(x2) 

array([ 0.    ,  2.0001])

In [67]:
(f(x2) - z)/ h

array([ -2.00010000e+00,   1.00005000e-04])

In [54]:
for x_temp in x1:
    print(x_temp)

2.000901
0.0


In [287]:
def test2(x):
    y = []
    y.insert(0, np.sin(x[0]))
    y.insert(1, np.sin(x[0]) + np.sin(x[1]))
    y.insert(2, np.sin(x[1]))
#     y.insert(3, np.sin(x[0]) + np.sin(x[0])
    return np.array(y)
    

In [293]:
x_test = np.array([0, np.pi/3])

In [294]:
test2(x_test)

array([ 0.       ,  0.8660254,  0.8660254])

In [295]:
numerical_jacobian(test2, x_test)

array([[ 1.        ,  0.        ],
       [ 1.        ,  0.49999567],
       [ 0.        ,  0.49999567]])

In [101]:
np.array(numerical_jacobian(test_func, x))

array([[  2.00000000e+00,  -9.99999994e-05],
       [  0.00000000e+00,   1.00000000e+00]])

In [304]:
jac_func = partial(numerical_jacobian, test2)

In [305]:
jac_func(x_test)

array([[ 1.        ,  0.        ],
       [ 1.        ,  0.49999567],
       [ 0.        ,  0.49999567]])

In [308]:
numerical_jacobian(jac_func, x_test)

array([[[ -1.00000008e-05,   0.00000000e+00],
        [ -9.99200722e-06,   0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00]],

       [[  0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,  -8.66030581e-01],
        [  0.00000000e+00,  -8.66030581e-01]]])