In [1]:
import numpy as np

In [7]:
def test_func(polar):
    x = polar[0] * np.sin(polar[1])
    y = polar[0] * np.cos(polar[1])
    return np.array([x,y])

=== Example 2: polar-Cartesian transformation ===

The transformation from [[polar coordinate system|polar coordinates]] {{math|(''r'', ''φ'')}} to [[Cartesian coordinate system|Cartesian coordinates]] (''x'', ''y''), is given by the function {{math|'''F''': ℝ<sup>+</sup> × [0, 2{{pi}}) → ℝ<sup>2</sup>}} with components:

:<math>\begin{align}
x &= r \cos \varphi ; \\
y &= r \sin \varphi .
\end{align}</math>
:<math>\mathbf J(r, \varphi) = \begin{bmatrix}
  \dfrac{\partial x}{\partial r} & \dfrac{\partial x}{\partial\varphi}\\[1em]
  \dfrac{\partial y}{\partial r} & \dfrac{\partial y}{\partial\varphi} \end{bmatrix}
= \begin{bmatrix}
  \cos\varphi & - r\sin \varphi \\
  \sin\varphi &   r\cos \varphi \end{bmatrix}</math>

The Jacobian determinant is equal to {{math|''r''}}.  This can be used to transform integrals between the two coordinate systems:
:<math>\iint_{\mathbf F(A)} f(x, y) \,dx \,dy = \iint_A f(r \cos \varphi, r \sin \varphi) \, r \, dr \, d\varphi .</math>


In [12]:
def jac_test_func(polar):
    r = polar[0]
    phi = polar[1]
    jac = np.array([[np.cos(phi), -r * np.sin(phi)],
                    [np.sin(phi), r * np.cos(phi)]])
    
    return jac
    

In [13]:
x = np.array([2, 0.0])

In [14]:
test_func(x)

array([ 0.,  2.])

In [15]:
jac_test_func(x)

array([[ 1., -0.],
       [ 0.,  2.]])

In [30]:
def numerical_jacobian(f, x, *args):
    z = f(x, *args)
    h = 1e-4
    n = x.shape[0]
    m = z.shape[0]
    jacobian  = np.zeros((m,n), dtype=float)
    for i in range(n):
        x1 = x
        x1[i] = x1[i] + h 
        
        jacobian[:, i] = (f(x1, *args) - z ) / h
    
    return jacobian

In [27]:
f = test_func
z = f(x)
h = 1e-4
n = x.shape[0]
m = z.shape[0]
jacobian  = np.zeros((m,n), dtype=float)

In [35]:
x1 = x
x1[0] = x1[0] + h
(f(x1)-z)/h

array([ 2.00169994,  4.99949973])

In [31]:
numerical_jacobian(test_func, x)

array([[  1.99999999e-04,   2.00049994e+00],
       [  9.99999980e-01,   9.99499905e-01]])