In [1]:
import os
import sys
import numpy as np


In [2]:
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)
    
from MomentMatching.StateModels import GaussianState
from MomentMatching.baseMomentMatch import UnscentedTransform, TaylorTransform, MonteCarloTransform

In [12]:
xx_mean = np.array([1.0, 1.0], dtype=float)
xx_sigma = np.array([[1, 0], [0, 1]], dtype=float)
distribution = GaussianState(xx_mean, xx_sigma)
A = np.array([[3, 0],
              [0, 1]], dtype=float)
B = np.array([0.0, 1.0], dtype=float)

In [14]:
A @ xx_sigma @ A.T 

array([[ 9.,  0.],
       [ 0.,  1.]])

In [20]:
def f(x, A=A, B=B):
    return np.dot(A, x) + B[:, np.newaxis]

In [21]:
UT = UnscentedTransform()
MCT = MonteCarloTransform(number_of_samples=1000)
TT = TaylorTransform()

In [22]:
models = [UT, TT]

In [23]:
pred = lambda x: x.predict(f, distribution)

In [24]:
result = []
for model in models:
    result.append(model.predict(f, distribution))

1.0


In [25]:
result[0]

(array([ 3.,  2.]), array([[ 9.,  0.],
        [ 0.,  1.]]), array([[ 3.,  0.],
        [ 0.,  1.]]))

In [26]:
result[1]

(array([[ 3.,  1.],
        [ 4.,  2.]]), array([[[ 9.,  0.],
         [ 9.,  0.]],
 
        [[ 0.,  1.],
         [ 0.,  1.]]]), array([[[ 3.,  0.],
         [ 3.,  0.]],
 
        [[ 0.,  1.],
         [ 0.,  1.]]]))